AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'db/*'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/*/*'
    - 'config/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
